name: C++ CI

on:
  pull_request

jobs:
  formatting-check:
    name: Formatting check
    runs-on: [self-hosted, ubuntu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check line breaks
        run: |
          sudo apt-get install -y dos2unix
          pushd $GITHUB_WORKSPACE
          ci-extra/check-lines.sh
          popd
      - name: Run clang-format style check
        # TODO use clang-format from a container
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '18'
          check-path: '.'

  test:
    needs: formatting-check
    name: "Test (${{ matrix.toolchain.name }}, ${{ matrix.build-type }})"

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - { name: Linux/GCC,   compiler: gcc-14 }
          - { name: Linux/Clang, compiler: clang-19 }
        build-type:
          - Release
          - Debug
          - RelWithDebInfo
          - Sanitized
          - SanitizedDebug

    runs-on: [self-hosted, ubuntu, "${{ matrix.toolchain.compiler }}"]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update tests
        run: |
          chown $(id -u):$(id -g) .
          git config --global user.name "John Doe"
          git config --global user.email johndoe@example.com
          source ci-extra/set-upstream.sh
          git remote add upstream "https://github.com/$UPSTREAM_REPO.git"
          git fetch upstream master
          if git merge-base --is-ancestor upstream/master @; then
            echo 'Tests are already up-to-date.'
            echo 'TESTS_UPDATED=0' >> $GITHUB_ENV
          else
            echo 'Updating tests...'
            git rebase upstream/master
            echo 'Tests updated.'
            echo 'TESTS_UPDATED=1' >> $GITHUB_ENV
          fi

      - name: Build
        run: |
          ci-extra/build.sh ${{ matrix.build-type }}
        env:
          CMAKE_TOOLCHAIN_FILE: "/opt/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Run tests
        run: |
          if [[ $TESTS_UPDATED -eq 1 ]]; then
            echo -e '\e[0;33mWARNING: Running a newer version of the tests than you have pushed.\e[0m'
          fi
          ci-extra/test.sh ${{ matrix.build-type }}

      - name: Run tests with valgrind
        if: ${{ matrix.build-type == 'RelWithDebInfo' }}
        run: |
          ci-extra/test-valgrind.sh ${{ matrix.build-type }}
